spring:
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
  #   user:
  #     name: lambert
  #     password: lambert
  servlet:
    multipart:
      max-file-size: 2096MB
      max-request-size: 2096MB
      # 开启文件上传服务
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://47.94.160.237:3306/app?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/app?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://47.94.160.237:3306/app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: lamberts
server:
  #  port: 8888
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
mybatis:
tomcat:
  uri-encoding: UTF-8